sudo: false

language: php

matrix:
  include:
    - php: 5.5
    - php: 5.6
      env:
        - TEST_COVERAGE=true
    - php: 7
      env: PHPSTAN=1
    - php: 7.1
    - php: hhvm
  allow_failures:
    - php: hhvm

before_install:
  - if [[ $TEST_COVERAGE != 'true' ]]; then phpenv config-rm xdebug.ini || return 0 ; fi
  - composer self-update
  - if [[ $TEST_COVERAGE == 'true' ]]; then composer require --dev --no-update satooshi/php-coveralls:^1.0 ; fi

install:
  - travis_retry composer install --dev --no-interaction

script:
    - mkdir -p build/logs
    - vendor/bin/phpunit -c phpunit.xml.dist --colors=always
    - if [[ $PHPSTAN = 1 ]]; then composer require --dev phpstan/phpstan:^0.6 && vendor/bin/phpstan analyse -c phpstan.neon -l 3 src; fi

after_script:
  - if [[ $TEST_COVERAGE == 'true' ]]; then vendor/bin/coveralls -v ; fi
