sudo: false

language: php

matrix:
  include:
    - php: 5.5
    - php: 5.6
    - php: 7
      env: PHPSTAN=1
    - php: 7.1
    - php: hhvm
  allow_failures:
    - php: hhvm

before_install:
  - composer self-update

install:
  - travis_retry composer install --no-interaction

script:
    - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover
    - if [[ $PHPSTAN = 1 ]]; then composer require --dev phpstan/phpstan:^0.6 && vendor/bin/phpstan analyse -c phpstan.neon -l 3 src; fi
